name: Test Draintasker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Test
      run: |
        touch $HOME/.ias3cfg
        python test/test-config.py
        python test/test-launch-transfers.py
        python test/test-pack-warcs.py
